spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Ratun@001724
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'
